name: langchain
channels:
  - menpo
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2023.05.30
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=3.0.10
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.1.0
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tornado=6.2
  - traitlets=5.7.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wget=1.16.3
  - wheel=0.38.4
  - zeromq=4.3.4
  - zipp=3.11.0
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anyio==3.7.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - async-lru==2.0.3
    - async-timeout==4.0.2
    - attrs==23.1.0
    - babel==2.12.1
    - beautifulsoup4==4.12.2
    - bionetgen==0.8.1
    - bleach==6.0.0
    - cement==3.0.8
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - colorlog==6.7.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - dataclasses-json==0.5.9
    - defusedxml==0.7.1
    - exceptiongroup==1.1.2
    - faiss-cpu==1.7.4
    - fastjsonschema==2.18.0
    - filelock==3.9.0
    - flatbuffers==23.5.26
    - fonttools==4.40.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.6.0
    - greenlet==2.0.2
    - huggingface-hub==0.16.3
    - idna==3.4
    - importlib-resources==5.12.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.18.4
    - jsonschema-specifications==2023.7.1
    - jupyter-events==0.6.3
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - kiwisolver==1.4.4
    - langchain==0.0.226
    - langchainplus-sdk==0.0.20
    - libclang==16.0.6
    - libroadrunner==2.4.0
    - lxml==4.9.3
    - markupsafe==2.1.2
    - marshmallow==3.19.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.7.2
    - mistune==3.0.1
    - mpmath==1.2.1
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.7.3
    - nbformat==5.9.1
    - nbopen==0.6
    - networkx==3.0
    - notebook==7.0.0
    - notebook-shim==0.2.3
    - numexpr==2.8.4
    - numpy==1.24.3
    - oauthlib==3.2.2
    - openai==0.27.8
    - openapi-schema-pydantic==1.2.4
    - opencv-python==4.8.0.74
    - overrides==7.3.1
    - packaging==23.1
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.17.1
    - protobuf==4.24.0
    - pyasn1==0.5.0
    - pycparser==2.21
    - pydantic==1.10.11
    - pylru==1.2.1
    - pyparsing==3.0.9
    - python-dotenv==1.0.0
    - python-json-logger==2.0.7
    - python-libsbml==5.20.1
    - pytz==2023.3
    - pywinpty==2.0.11
    - pyyaml==6.0
    - referencing==0.30.0
    - regex==2023.6.3
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.9.2
    - safetensors==0.3.1
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.18
    - sympy==1.11.1
    - tenacity==8.2.2
    - tensorboard-data-server==0.7.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - tiktoken==0.4.0
    - timm==0.9.2
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.0.1+cu117
    - torchaudio==2.0.2+cu117
    - torchvision==0.15.2+cu117
    - tqdm==4.65.0
    - transformers==4.30.2
    - typing-extensions==4.5.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==1.26.16
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - werkzeug==2.3.6
    - wrapt==1.15.0
    - xmltodict==0.13.0
    - yarl==1.9.2
